spring.application.name=comidasrapidas

spring.datasource.url=jdbc:postgresql://db.kimhitdsfmwjbxvdgnoc.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=Comidas123@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect